apiVersion: v1
kind: Secret
metadata:
  name: bot-service-secrets
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: replace-me
  VK_ACCESS_TOKEN: ""
  INTERNAL_API_TOKEN: replace-me
  BOT_USER_DB_PASSWORD: replace-me
  BOT_REDIS_PASSWORD: replace-me
