apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-service
  ports:
    - name: http
      port: 8081
      targetPort: http
    - name: management
      port: 9081
      targetPort: management
