apiVersion: v1
kind: Service
metadata:
  name: tracker-service
spec:
  selector:
    app: tracker-service
  ports:
    - name: http
      port: 8082
      targetPort: http
    - name: management
      port: 9082
      targetPort: management
