CREATE TABLE service_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    chat_id VARCHAR(128) NOT NULL,
    subscriptions_revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_service_users_identity UNIQUE (bot_id, user_id, chat_id),
    CONSTRAINT ck_service_users_revision CHECK (subscriptions_revision >= 0)
);

CREATE TABLE tracked_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(253) NOT NULL,
    address VARCHAR(2048) NOT NULL,
    tracking_revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_tracked_links_address UNIQUE (address),
    CONSTRAINT ck_tracked_links_revision CHECK (tracking_revision >= 0)
);

CREATE INDEX ix_tracked_links_domain ON tracked_links (domain);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    link_id BIGINT NOT NULL,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES service_users (id),
    CONSTRAINT fk_subscriptions_link FOREIGN KEY (link_id) REFERENCES tracked_links (id),
    CONSTRAINT uk_subscriptions_user_link UNIQUE (user_id, link_id)
);

CREATE INDEX ix_subscriptions_link_user ON subscriptions (link_id, user_id);

CREATE TABLE subscription_tags (
    subscription_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    tag VARCHAR(256) NOT NULL,
    PRIMARY KEY (subscription_id, position),
    CONSTRAINT fk_subscription_tags_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE
);

CREATE TABLE subscription_filters (
    subscription_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    expression VARCHAR(256) NOT NULL,
    PRIMARY KEY (subscription_id, position),
    CONSTRAINT fk_subscription_filters_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE
);
